version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run test
          command: |
            npm run test
  build_and_deploy:
    docker:
      - image: circleci/node:8.10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies and build production
          command: |
            npm install
            npm run build
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            ./scripts/pack.sh
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /feature\/.*|/hotfix\/.*/
  